#!/bin/bash

VERSION=0.1.9

##########################################################################################
#                                                                                        #
# 4Toolz Collection 0.1.9 (4Toolz)                                                       #
#                                                                                        #
# Idea / Written by Sebastian Vivian Gresser - All Rights Reserved                       #
#                                                                                        #
# Copyright (C) by Sebastian Vivian Gresser - All Rights Reserved                        #
#                                                                                        #
##########################################################################################
#                                                                                        #
# WARRANTY AND RESPONSIBILITY: There is no warranty! You are responsible on your own     #
#                              how you are using this set of tools.                      #
#                                                                                        #
##########################################################################################
#                                                                                        #
#                                       CONTENTS:                                        #
#                                                                                        #
##########################################################################################
#                                                                                        #
########################################## 4NET ##########################################
#                                                                                        #
# <->4utoBl4ck: will blackhole any suspicious ips or ranges of ips resolved from a given #
#               domainlist                                                               #
#  |-> 4utoBl4ck needs Grsecurity's blackhole patch for ip route to work properly!!!     #
#  with cron you can add this to auto-blackhole any network if you have their            #
#  load balance domain names                                                             #
#                                                                                        #
# <->4routing a small usefull tool for changing your routing on the fly using a          #
#  text editor                                                                           #
#                                                                                        #
# <->4static_hosts a small usefull tool for generating a static hosts config             #
#  which can be used with 4 routing if you do not trust your nameserver provider         #
#                                                                                        #
# <->4roter_masq forwarding nets on different devices                                    #
#                                                                                        #
# <->4GhostInTheNet.sh stealthing a linux device by disabling arp and randomizing mac    #
#    modified version of https://github.com/cryptolok/GhostInTheNet                      #
###################################### 4MAINTENANCE ######################################
#                                                                                        #
# <->4git: will start multiple based git pull or clone processes                         #
#  |->                                                                                   #
#  with cron you can add this to update your git repo collection regularly               #
#                                                                                        #
# <->4regen_pax_flags: - regenerating default pax flags using paxctl-ng and migrate-pax  #
#  |->                                                                                   #
#  usefull if your system is vanilla like and libs and binaries are compiled from sources#
#  to benefit from the generated individual entropy of your kernel/compilers             #
#                                                                                        #
######################################## 4BACKUP #########################################
#                                                                                        #
# <->mkstage4_gentoo: will create a stage 4 of your operating system                     #
#  |->                                                                                   #
#  usefull tool for backup and making your own linux repo stage4s including xattrs       #
#                                                                                        #
######################################## 4WEB ############################################
#                                                                                        #
# <->monetize_link: will reassemble the given link and its structure to comply with      #
#                   the standards of different internet platforms like eBay and          #
#                   comparable (revenue/monetarization)                                  #
#                                                                                        #
###################################### 4TELEGRAM #########################################
#                                                                                        #
# <->tmdl.py: a small helper script for exporting chats/media files/etc.                 #
#  |                                                                                     #
#  |->tmdl_gui.py: a gui (tkinter) to manage several channels at the same time.          #
#   |->tmdl_queue: example channel configurations.                                       #
#                                                                                        #
#                                                                                        #
##########################################################################################
